FROM nginx:latest

RUN rm -rf /usr/share/nginx/html/*
RUN mkdir -p /usr/share/nginx/html/sef-cli
COPY ./dist /usr/share/nginx/html/sef-cli

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
